import { KOLPlatform, KOLStatus, KOL, SopPackage, Campaign } from "./types";

export const INITIAL_CAMPAIGNS: Campaign[] = [
  { id: "CAMP-001", name: "Green Tea Facial Care", brand: "Brand A - Organic Glow" },
  { id: "CAMP-002", name: "Super Kitchen Seasoning", brand: "Brand B - Cook Master" },
  { id: "CAMP-003", name: "Modern Skin Serum", brand: "Brand C - Beauty Vibe" },
];

export const INITIAL_KOLS: KOL[] = [
  {
    id: "KOL-001",
    name: "HealthyLife.Review",
    platform: KOLPlatform.TIKTOK,
    followers: 150000,
    status: KOLStatus.BRAND_REVIEW,
    contact: "คุณจอย (081-xxx-xxxx)",
    clientPrice: 15000,
    netCost: 12000,
    profit: 3000,
    behavioralRemark: "ทำยอดมีเดียสุขภาพสูง ดีสำหรับสินค้าธรรมชาติแต่อาจจะตอบแชทช้าเล็กน้อย",
    dealConditions: "แถมโพสลง IG Story ให้ 1 ชิ้นฟรีหากชำระเงินมัดจำภายใน 3 วัน",
    draftDeadline: "2026-06-20",
    liveDeadline: "2026-06-25",
    draftLink: "https://drive.google.com/draft1",
    liveLink: "",
    profileUrl: "https://www.tiktok.com/@healthylife.review",
    campaignId: "CAMP-001",
  },
  {
    id: "KOL-002",
    name: "CookWithMe_TH",
    platform: KOLPlatform.INSTAGRAM,
    followers: 85000,
    status: KOLStatus.LIVE,
    contact: "คุณตั้ม (Line: tum_cook)",
    clientPrice: 10000,
    netCost: 8000,
    profit: 2000,
    behavioralRemark: "ส่งงานตรงเวลา ตัดต่อประณีตสวยงามมาก",
    dealConditions: "ส่งวัตถุดิบและจานยึดแบรนด์ให้ล่วงหน้า 5 วันก่อนวันถ่ายทำจริง",
    draftDeadline: "2026-06-10",
    liveDeadline: "2026-06-14",
    draftLink: "https://drive.google.com/draft2",
    liveLink: "https://instagram.com/live2",
    profileUrl: "https://www.instagram.com/cookwithme_th",
    campaignId: "CAMP-002",
  },
  {
    id: "KOL-003",
    name: "BeautyVibe_Official",
    platform: KOLPlatform.TIKTOK,
    followers: 320000,
    status: KOLStatus.CONTRACT,
    contact: "ติดต่อโดยตรง (DM IG)",
    clientPrice: 25000,
    netCost: 20000,
    profit: 5000,
    behavioralRemark: "ผู้ติดตามเยอะ คอนเทนต์บิวตี้หรูหรา",
    dealConditions: "ขอสิทธิ์พรีวิวคลิปก่อนอัปโหลดขั้นต่ำ 48 ชม.",
    draftDeadline: "2026-06-28",
    liveDeadline: "2026-07-02",
    draftLink: "",
    liveLink: "",
    profileUrl: "https://www.tiktok.com/@beautyvibe_official",
    campaignId: "CAMP-003",
  },
];

export const SOP_PACKAGES: SopPackage[] = [
  {
    id: 1,
    title: "Matching & Selection",
    energy: "Very Low Energy",
    color: "emerald",
    definition: "กระบวนการคัดเลือกอินฟลูฯ ที่ตรงกับกลุ่มเป้าหมายและภาพลักษณ์แบรนด์ โดยใช้ Data-driven approach เพื่อเซฟแรงที่สุด",
    steps: [
      "วิเคราะห์กลุ่มเป้าหมายของสินค้า (Audience Analysis)",
      "คัดกรองจาก Database แยกรายชื่อแนะนำระดับ Stars หรือคัดกรอง Blacklist",
      "ตรวจสอบประวัติย้อนหลัง ผลิตงานเก่า และความเสี่ยงจากดราม่า",
      "รวบรวมทำ Shortlist นำเสนอสรุปเรทราคาให้แบรนด์พิจารณาเคาะเลือก",
    ],
    deliverables: "KOL Shortlist (Excel/PDF) พร้อมช่องทางและสถิติเรทราคาอัปเดต",
    guard: "ห้ามเลือกอินฟลูฯ ที่เคยมีพฤติกรรมทำงานช้าหรือติดแบล็กลิสต์ในระบบ CRM เด็ดขาด ยกเว้นแต่แบรนด์จะเซ็นไฟเขียวพิเศษ",
  },
  {
    id: 2,
    title: "Master Brief & Content Direction",
    energy: "Medium Energy",
    color: "blue",
    definition: "การเตรียมม스터บรีฟและโครงสร้างคริเอทีฟบรีฟ (Hook, Body, CTA) ชุดเดียวที่สามารถส่งให้ KOL ทำงานต่อได้ทันทีและถูกต้อง",
    steps: [
      "กำหนด USP (Unique Selling Point) ของผลิตภัณฑ์หลัก 3 ข้อเป็นหลักเด่น",
      "วางคอร์โครงสร้าง Storyline สคริปต์วิดีโอสั้น (Hook 3 วิแรก, Body, CTA แนะนำ)",
      "จัดเตรียม Asset Pack เช่น โลโก้แคมเปญ ฟอนต์กำหนด ภาพถ่ายสินค้ามุมสวยงาม",
      "ระบุ Do's (สิ่งที่แนะนำให้ทำ) และ Don'ts (ข้อห้ามเคลม อย. และข้อห้ามตามกฎหมาย) ชัดเจน",
    ],
    deliverables: "เอกสาร Master Brief สำหรับ KOL (PDF / Google Docs Link)",
    guard: "เนื้อหาบรีฟในเอกสารต้องไม่เกิน 2 หน้ากระดาษ เพื่อป้องกันไม่อ่านและทำหลุดบรีฟ",
  },
  {
    id: 3,
    title: "Celeb & Tier 1 Coordinator",
    energy: "High Energy",
    color: "amber",
    definition: "การสื่อสารและควบคุมข้อตกลงงานกับ KOL ระดับพรีเมียม/เซเลบริตี้ ที่ต้องการคุณภาพงานที่สมบูรณ์และสัญญาทางกฎหมายที่รัดกุม",
    steps: [
      "เจรจาเงื่อนไขพิเศษ เช่น ลิขสิทธิ์การนำคลิปไปยิงแอดโฆษณา (Usage Right) 3 เดือน",
      "ร่างและส่งสัญญาจ้าง ตรวจสอบผู้แทนเซ็นสัญญา และล็อกวันเซ็นสัญญาสำเร็จ",
      "จัดส่งแพ็กเกจสินค้ามูลค่าสูงพร้อมข้อมูลสิทธิพิเศษและคัมภีร์บรีฟ",
      "คุมการตรวจแก้งาน (ดราฟต์คลิป) ผ่านผู้จัดการส่วนตัว ให้เป็นไปตามกรอบคิว",
    ],
    deliverables: "Signed Agreement / Tracking Sheet ของ KOL แต่ละท่าน",
    guard: "ต้องเซ็นสัญญาและชำระมัดจำสมบูรณ์ 100% ก่อนจัดส่งสินค้าและอุปกรณ์ราคาสูงไปเด็ดขาด",
  },
  {
    id: 4,
    title: "On-site & Event Sync",
    energy: "High Energy",
    color: "rose",
    definition: "การควบคุมคิวและดูแลพฤติกรรมการผลิตสื่อ/อัปโหลดสดของ KOL หน้างานจริงเพื่อไม่ให้เวลาเคลื่อนและครอบคลุมทุกจุดถ่ายภาพสำคัญ",
    steps: [
      "เตรียม Call Sheet และ Sequence ตารางรันคิวของ KOL แต่ละช่วงนาที",
      "ต้อนรับที่จุดพัก และซักซ้อมบรีฟหน้างานก่อนออนแอนด์สเตจจริง",
      "ตรวจสอบมุมกล้อง การแต่งกาย แสง สี และฉากสแตนด์ร่วมกับฝ่ายแสง",
      "คุมการอัปโหลดหรือโพสต์สื่อเรียลไทม์ (IG Story / Live) หน้างานทันที",
    ],
    deliverables: "On-site Checklist Complete / Raw Footage และ Log วันงาน",
    guard: "ห้ามปล่อย KOL ออกนอกสถานที่เด็ดขาดหากทีมงานยังตรวจเช็ก Footage วิดีโอและภาพถ่ายไม่ครบถ้วน",
  },
  {
    id: 5,
    title: "Campaign Kit & Tracking",
    energy: "Ultra Low Energy",
    color: "slate",
    definition: "การสรุปผล ประเมินพฤติกรรม และจัดทำระบบคลังเทมเพลตมาตรฐานในการใช้งานต่อยอดเซฟแรงในอนาคต",
    steps: [
      "เก็บรวมรวมสถิติจริง (View, Likes, Shares, Engagement, Link Clicks)",
      "วิเคราะห์ประเมินคะแนนพฤติกรรมการทำงานของ KOL (Behavior Remark)",
      "สรุปข้อมูลคู่มือฉบับพกพาประกอบสัญญาและคลังเครื่องมือส่งมอบแบรนด์",
      "ยื่นเรื่องปิดงบการเงินและรอนายทุนอนุมัติกำไรเอเจนซี่",
    ],
    deliverables: "Summary Report แดชบอร์ดผลงานพร้อมแบบจำลอง Google Space",
    guard: "ส่งมอบงานให้เสร็จภายใน 7 วันหลังแคมเปญสิ้นสุดเพื่อความแม่นยำของสถิติศูนย์ข้อมูล",
  },
];
